// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MittsModsApi.Data;

#nullable disable

namespace MittsModsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406090000_AddIsFavourite")]
    partial class AddIsFavourite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MittsModsApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MittsModsApi.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "PC",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "XBOX",
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "X360",
                            Name = "Xbox 360"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "XONE",
                            Name = "Xbox One"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "XSX",
                            Name = "Xbox Series S/X"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "PS1",
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PS2",
                            Name = "PlayStation 2"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "PS3",
                            Name = "PlayStation 3"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "PS4",
                            Name = "PlayStation 4"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "PS5",
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "PSP",
                            Name = "PSP"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "VITA",
                            Name = "PS Vita"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "NES",
                            Name = "NES"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "SNES",
                            Name = "SNES"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "N64",
                            Name = "Nintendo 64"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "GCN",
                            Name = "GameCube"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "WII",
                            Name = "Wii"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "WIIU",
                            Name = "Wii U"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "NSW",
                            Name = "Nintendo Switch"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "NSW2",
                            Name = "Nintendo Switch 2"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "GB",
                            Name = "Game Boy"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "GBC",
                            Name = "Game Boy Color"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "GBA",
                            Name = "Game Boy Advance"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "NDS",
                            Name = "Nintendo DS"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "3DS",
                            Name = "Nintendo 3DS"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "DC",
                            Name = "Sega Dreamcast"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "OTH",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MittsModsApi.Models.UserEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hardware")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HoursPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlatformId");

                    b.ToTable("UserEntries");
                });

            modelBuilder.Entity("MittsModsApi.Models.UserEntry", b =>
                {
                    b.HasOne("MittsModsApi.Models.Game", "Game")
                        .WithMany("UserEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MittsModsApi.Models.Platform", "Platform")
                        .WithMany("UserEntries")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MittsModsApi.Models.Game", b =>
                {
                    b.Navigation("UserEntries");
                });

            modelBuilder.Entity("MittsModsApi.Models.Platform", b =>
                {
                    b.Navigation("UserEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
