// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MittsModsApi.Data;

#nullable disable

namespace MittsModsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MittsModsApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MittsModsApi.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "PC",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "DC",
                            Name = "Sega Dreamcast"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "X360",
                            Name = "Xbox 360"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NSW",
                            Name = "Nintendo Switch"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "NSL",
                            Name = "Nintendo Switch Lite"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "PS2",
                            Name = "PlayStation 2"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PS3",
                            Name = "PlayStation 3"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "PS4",
                            Name = "PlayStation 4"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "GBA",
                            Name = "Game Boy Advance"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "NDS",
                            Name = "Nintendo DS"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "3DS",
                            Name = "Nintendo 3DS"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "OTH",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MittsModsApi.Models.UserEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievementsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HoursPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlatformId");

                    b.ToTable("UserEntries");
                });

            modelBuilder.Entity("MittsModsApi.Models.UserEntry", b =>
                {
                    b.HasOne("MittsModsApi.Models.Game", "Game")
                        .WithMany("UserEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MittsModsApi.Models.Platform", "Platform")
                        .WithMany("UserEntries")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MittsModsApi.Models.Game", b =>
                {
                    b.Navigation("UserEntries");
                });

            modelBuilder.Entity("MittsModsApi.Models.Platform", b =>
                {
                    b.Navigation("UserEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
